# NOTE: Generated By HttpRunner v3.1.4
# FROM: ./testcases/testcase_aba_bsb.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTestcaseAbaBsb(HttpRunner):
    @pytest.mark.parametrize(
        "param", Parameters({"account_routing_type1": ["bsb", "aba"]})
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("/api/v1/beneficiaries/create")
        .base_url("https://api-demo.airwallex.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("get_Token")
            .post("/api/v1/authentication/login")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/json",
                    "x-api-key": "2308e2dd300f6b959b7f4e0a52ba9181186fc92f075f7e64ee9fa0b6b1ada094c39c9a9f39f06693d06b17067f78d4e7",
                    "x-client-id": "KJbr_Xs5TLmhY03JWSi3NQ",
                }
            )
            .with_data("")
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("aba_bsb_CN")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "$account_routing_type1",
                            "account_routing_value1": "021000021",
                            "bank_country_code": "CN",
                            "bank_name": "JP Morgan Chase Bank",
                            "swift_code": "PCBCCNBJSZX",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["SWIFT"],
                }
            )
            .validate()
            .assert_equal("status_code", 201)
            .assert_equal(
                "body.beneficiary.bank_details.account_routing_type1",
                "$account_routing_type1",
            )
            .assert_equal("body.beneficiary.bank_details.bank_country_code", "CN")
        ),
        Step(
            RunRequest("bsb_AU")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Melbourne",
                            "country_code": "AU",
                            "postcode": "3000",
                            "state": "VIC",
                            "street_address": "18 William Street",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "716978952",
                            "account_routing_type1": "bsb",
                            "bank_country_code": "AU",
                            "bank_name": "National Australia Bank Limited",
                            "swift_code": "NATAAU3302S",
                        },
                        "company_name": "Complete Concrete Pty Ltd",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "Complete Concrete Pty Ltd",
                    "payment_methods": ["SWIFT"],
                }
            )
            .validate()
            .assert_equal("status_code", 201)
            .assert_equal("body.beneficiary.bank_details.account_routing_type1", "bsb")
            .assert_equal("body.beneficiary.bank_details.bank_country_code", "AU")
        ),
        Step(
            RunRequest("bsb_US")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "bsb",
                            "account_routing_value1": "021000021",
                            "bank_country_code": "US",
                            "bank_name": "JP Morgan Chase Bank",
                            "local_clearing_system": "ACH",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["LOCAL"],
                }
            )
            .validate()
            .assert_equal("status_code", 400)
            .assert_equal("body.message", "Should equal aba")
            .assert_equal(
                "body.source", "beneficiary.bank_details.account_routing_type1"
            )
        ),
        Step(
            RunRequest("aba_US_9")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "aba",
                            "account_routing_value1": "021000021",
                            "bank_country_code": "US",
                            "bank_name": "JP Morgan Chase Bank",
                            "local_clearing_system": "ACH",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["LOCAL"],
                }
            )
            .validate()
            .assert_equal("status_code", 201)
            .assert_equal("body.beneficiary.bank_details.account_routing_type1", "aba")
            .assert_equal("body.beneficiary.bank_details.bank_country_code", "US")
        ),
        Step(
            RunRequest("aba_US_10")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "aba",
                            "account_routing_value1": "0210000210",
                            "bank_country_code": "US",
                            "bank_name": "JP Morgan Chase Bank",
                            "local_clearing_system": "ACH",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["LOCAL"],
                }
            )
            .validate()
            .assert_equal("status_code", 400)
            .assert_equal("body.message", "Should be 9 characters long")
        ),
        Step(
            RunRequest("aba_AU")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {
                            "personal_email": "AUjohn.walker@gmail.com"
                        },
                        "address": {
                            "city": "Melbourne",
                            "country_code": "AU",
                            "postcode": "3000",
                            "state": "VIC",
                            "street_address": "18 William Street",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "716978952",
                            "account_routing_type1": "aba",
                            "bank_country_code": "AU",
                            "bank_name": "National Australia Bank Limited",
                            "swift_code": "NATAAU3302S",
                        },
                        "company_name": "Complete Concrete Pty Ltd",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "Complete Concrete Pty Ltd",
                    "payment_methods": ["SWIFT"],
                }
            )
            .validate()
            .assert_equal("status_code", 400)
            .assert_equal("body.message", "Should equal bsb")
        ),
    ]


if __name__ == "__main__":
    TestCaseTestcaseAbaBsb().test_start()
