# NOTE: Generated By HttpRunner v3.1.4
# FROM: ./testcases/testcase_swift_code.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTestcaseSwiftCode(HttpRunner):

    config = (
        Config("/api/v1/beneficiaries/create")
        .base_url("https://api-demo.airwallex.com")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("get_Token")
            .post("/api/v1/authentication/login")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/json",
                    "x-api-key": "2308e2dd300f6b959b7f4e0a52ba9181186fc92f075f7e64ee9fa0b6b1ada094c39c9a9f39f06693d06b17067f78d4e7",
                    "x-client-id": "KJbr_Xs5TLmhY03JWSi3NQ",
                }
            )
            .with_data("")
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 201)
        ),
        Step(
            RunRequest("swift_code_CN")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "aba",
                            "bank_country_code": "CN",
                            "bank_name": "JP Morgan Chase Bank",
                            "swift_code": "ICBKCNBJ",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["SWIFT"],
                }
            )
            .validate()
            .assert_equal("status_code", 201)
            .assert_equal("body.beneficiary.bank_details.swift_code", "ICBKCNBJ")
            .assert_equal("body.beneficiary.bank_details.bank_country_code", "CN")
        ),
        Step(
            RunRequest("swift_code_US")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "aba",
                            "bank_country_code": "US",
                            "bank_name": "JP Morgan Chase Bank",
                            "swift_code": "CHASUS33",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["SWIFT"],
                }
            )
            .validate()
            .assert_equal("status_code", 201)
            .assert_equal("body.beneficiary.bank_details.swift_code", "CHASUS33")
            .assert_equal("body.beneficiary.bank_details.bank_country_code", "US")
        ),
        Step(
            RunRequest("swift_code_AU")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "aba",
                            "bank_country_code": "AU",
                            "bank_name": "JP Morgan Chase Bank",
                            "swift_code": "CITIAUSX",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["SWIFT"],
                }
            )
            .validate()
            .assert_equal("status_code", 201)
            .assert_equal("body.beneficiary.bank_details.swift_code", "CITIAUSX")
            .assert_equal("body.beneficiary.bank_details.bank_country_code", "AU")
        ),
        Step(
            RunRequest("swift_code_CN_abnormal")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "aba",
                            "bank_country_code": "CN",
                            "bank_name": "JP Morgan Chase Bank",
                            "swift_code": "ICBKUSBJ",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["SWIFT"],
                }
            )
            .validate()
            .assert_equal("status_code", 400)
            .assert_equal(
                "body.message", "Should be a valid and supported SWIFT code / BIC"
            )
        ),
        Step(
            RunRequest("swift_code_US_abnormal")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "aba",
                            "bank_country_code": "US",
                            "bank_name": "JP Morgan Chase Bank",
                            "swift_code": "CHAUS33AAA",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["SWIFT"],
                }
            )
            .validate()
            .assert_equal("status_code", 400)
            .assert_equal(
                "body.message", "Should be a valid and supported SWIFT code / BIC"
            )
        ),
        Step(
            RunRequest("swift_code_AU_abnormal")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "aba",
                            "bank_country_code": "US",
                            "bank_name": "JP Morgan Chase Bank",
                            "swift_code": "CITIAUSXAAA",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["SWIFT"],
                }
            )
            .validate()
            .assert_equal("status_code", 400)
            .assert_contains(
                "body.message",
                "The SWIFT code / BIC should match the bank location selected",
            )
        ),
        Step(
            RunRequest("swift_code_AU_abnormal_long")
            .post("/api/v1/beneficiaries/create")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Bearer $token"}
            )
            .with_json(
                {
                    "beneficiary": {
                        "additional_info": {"personal_email": "john.walker@gmail.com"},
                        "address": {
                            "city": "Seattle",
                            "country_code": "US",
                            "postcode": "98104",
                            "state": "Washington",
                            "street_address": "412 5th Avenue",
                        },
                        "bank_details": {
                            "account_currency": "USD",
                            "account_name": "John Walker",
                            "account_number": "50001121",
                            "account_routing_type1": "aba",
                            "bank_country_code": "AU",
                            "bank_name": "JP Morgan Chase Bank",
                            "swift_code": "CITIAUSXAAAA",
                        },
                        "company_name": "ABC University",
                        "entity_type": "COMPANY",
                    },
                    "nickname": "ABC University",
                    "payment_methods": ["SWIFT"],
                }
            )
            .validate()
            .assert_equal("status_code", 400)
            .assert_equal(
                "body.message", "Should be a valid and supported SWIFT code / BIC"
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseTestcaseSwiftCode().test_start()
